apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-aof7
resources:
- ../../base

patches:
  - path: patch-env.yaml
    target:
      kind: Secret
      name: mc-env
      namespace: minecraft-aof7
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: all-of-fabric-7
      namespace: minecraft-aof7
  - path: patch-delete-minecraft-container.yaml
    target:
      name: all-of-fabric-7
      namespace: minecraft-aof7
