apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-aof7
resources:
  - ../../base
  - namespace.yaml
secretGenerator:
  - name: mc-env
    envs:
      - mc-env.env
    type: Opaque
patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: all-of-fabric-7
      namespace: minecraft-aof7
  - path: patch-delete-minecraft-container.yaml
    target:
      name: all-of-fabric-7
      namespace: minecraft-aof7
images:
  - name: docker.io/chrisroth667/minecraft
    newName: docker.io/chrisroth667/aof7
    newTag: "2.5.3"
