apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-world.yaml
  - pvc-backup.yaml
  - serviceaccount.yaml
  - cm-server-setup-config.yaml
  - cm-server-properties.yaml
  - cm-backup.yaml
  - secret-env.yaml
  - secret-mcrcon.yaml
  - service.yaml
  - deployment.yaml
  - cm-mcrcon.yaml
  - cm-startserver.yaml
