apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-storage
  namespace: minecraft-aof7
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: netapp
  volumeMode: Filesystem
