apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  selector:
    app: minecraft
  ports:
    - name: game
      protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  externalTrafficPolicy: Local
