apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-atm10
resources:
  - ../../base
  - namespace.yaml
secretGenerator:
  - name: mc-env
    envs:
      - mc-env.env
    type: Opaque
patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: all-the-mods-10
      namespace: minecraft-atm10
  - path: patch-delete-minecraft-container.yaml
    target:
      name: all-the-mods-10
      namespace: minecraft-atm10
images: 
  - name: docker.io/chrisroth667/minecraft
    newName: docker.io/chrisroth667/atm10
    newTag: "5.0"

